name: Daily Auto Commit with Date

on:
  schedule:
    - cron: '0 2 * * *'   # 08:00 Бишкек убактысы менен
    - cron: '0 6 * * *'   # 12:00 Бишкек
    - cron: '0 8 * * *'   # 14:00 Бишкек
    - cron: '0 10 * * *'  # 16:00 Бишкек
    - cron: '0 12 * * *'  # 18:00 Бишкек
    - cron: '0 14 * * *'  # 20:00 Бишкек
  workflow_dispatch: # Кол менен да иштетсе болот

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "mar4ik"
          git config user.email "mar4ikgithub@gmail.com"

      - name: Update date in file
        run: |
          echo "Last update: $(date '+%Y-%m-%d %H:%M:%S')" > update.txt
          git add update.txt
          git commit -m "Auto-update: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mar4ikdev/github.git
